<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Delson-Roy" failures="1" tests="3" name="Test" time="58.519" errors="0" timestamp="2024-04-04T18:07:57 GMT-04:00">
  <testcase classname="script.InvalidLogin" name="testInvalidLogin" time="2.25"/>
  <testcase classname="script.ValidLogin" name="testValidLogin" time="20.655">
    <skipped/>
  </testcase> <!-- testValidLogin -->
  <testcase classname="script.ValidLogin" name="testValidLogin" time="20.678">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at script.ValidLogin.testValidLogin(ValidLogin.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- testValidLogin -->
  <testcase classname="generic.BaseTest" name="@BeforeSuite intReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite intReport -->
  <testcase classname="generic.BaseTest" name="@AfterSuite generateReport" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite generateReport -->
</testsuite> <!-- Test -->
